name: ecommerce_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: 
  flutter_bloc: 
  persistent_bottom_nav_bar_v2: any
  firebase_auth:
  firebase_core:
  cloud_firestore: 
  provider:
  flutter_rating_bar: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.11.0
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/shopping.png"


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/



